# Generated by Django 5.2.1 on 2025-08-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('desgination', models.CharField(max_length=100)),
            ],
        ),
    ]
