# Generated by Django 5.2.1 on 2025-08-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='desgination',
            new_name='designation',
        ),
    ]
